# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        cryptography-version: ["cryptography==0.1", "cryptography==0.2", "cryptography==0.2.1", "cryptography==0.2.2", "cryptography==0.3", "cryptography==0.4", "cryptography==0.5", "cryptography==0.5.1", "cryptography==0.5.2", "cryptography==0.5.3", "cryptography==0.5.4", "cryptography==0.6", "cryptography==0.6.1", "cryptography==0.7", "cryptography==0.7.1", "cryptography==0.7.2", "cryptography==0.8", "cryptography==0.8.1", "cryptography==0.8.2", "cryptography==0.9", "cryptography==0.9.1", "cryptography==0.9.2", "cryptography==0.9.3", "cryptography==1.0", "cryptography==1.0.1", "cryptography==1.0.2", "cryptography==1.1", "cryptography==1.1.1", "cryptography==1.1.2", "cryptography==1.2", "cryptography==1.2.1", "cryptography==1.2.2", "cryptography==1.2.3", "cryptography==1.3", "cryptography==1.3.1", "cryptography==1.3.2", "cryptography==1.3.3", "cryptography==1.3.4", "cryptography==1.4", "cryptography==1.5", "cryptography==1.5.1", "cryptography==1.5.2", "cryptography==1.5.3", "cryptography==1.6", "cryptography==1.7", "cryptography==1.7.1", "cryptography==1.7.2", "cryptography==1.8", "cryptography==1.8.1", "cryptography==1.8.2", "cryptography==1.9", "cryptography==2.0", "cryptography==2.0.1", "cryptography==2.0.2", "cryptography==2.0.3", "cryptography==2.1", "cryptography==2.1.1", "cryptography==2.1.2", "cryptography==2.1.3", "cryptography==2.1.4", "cryptography==2.2", "cryptography==2.2.1", "cryptography==2.2.2", "cryptography==2.3", "cryptography==2.3.1", "cryptography==2.4", "cryptography==2.4.1", "cryptography==2.4.2", "cryptography==2.5", "cryptography==2.6", "cryptography==2.6.1", "cryptography==2.7", "cryptography==2.8", "cryptography==2.9", "cryptography==2.9.1", "cryptography==2.9.2", "cryptography==3.0", "cryptography==3.1", "cryptography==3.1.1", "cryptography==3.2", "cryptography==3.2.1", "cryptography==3.3", "cryptography==3.3.1", "cryptography==3.3.2", "cryptography==3.4", "cryptography==3.4.1", "cryptography==3.4.2", "cryptography==3.4.3", "cryptography==3.4.4", "cryptography==3.4.5", "cryptography==3.4.6", "cryptography==3.4.7", "cryptography==3.4.8", "cryptography==35.0.0", "cryptography==36.0.0", "cryptography==36.0.1", "cryptography==36.0.2", "cryptography==37.0.0", "cryptography==37.0.1", "cryptography==37.0.2", "cryptography==37.0.4", "cryptography==38.0.0", "cryptography==38.0.1", "cryptography==38.0.3", "cryptography==38.0.4", "cryptography==39.0.0", "cryptography==39.0.1", "cryptography==39.0.2", "cryptography==40.0.0", "cryptography==40.0.1", "cryptography==40.0.2", "cryptography==41.0.0", "cryptography==41.0.1", "cryptography==41.0.2", "cryptography==41.0.3", "cryptography==41.0.4", "cryptography==41.0.5", "cryptography==41.0.6", "cryptography==41.0.7", "cryptography==42.0.0", "cryptography==42.0.1", "cryptography==42.0.2", "cryptography==43.0.0.dev1", "cryptography"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install tqdm
        pip install ${{ matrix.cryptography-version }}
        pip install .
    - name: Test with unittest
      run: |
        python tests/tests.py
