# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
  issues:
    types: [opened]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
        cryptography-version: ['cryptography==36.0.2', 'cryptography==37.0.4', 'cryptography==38.0.4', 'cryptography==39.0.2', 'cryptography==40.0.2', 'cryptography==41.0.7','cryptography==42.0.2', 'cryptography']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install tqdm
        pip install ${{ matrix.cryptography-version }}
        pip install .
    - name: Test with unittest
      run: |
        python tests/tests.py
